######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 8 15:57:34 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src

# Input
HEADERS += VideoStabilization.h
SOURCES += main.cpp VideoStabilization.cpp
