######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 17:01:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src

# Input
SOURCES += main.cpp
